name: Job Outputs

on: workflow_dispatch

jobs:
  jobA:
    runs-on: ubuntu-latest
    outputs:
      random_number: ${{ steps.gen.outputs.number }}
    steps:
      - id: gen
        run: echo "number=$RANDOM" >> $GITHUB_OUTPUT

  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - run: |
          echo "NÃºmero recibido: ${{ needs.jobA.outputs.random_number }}"
