name: Artifacts Example

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola desde el artefacto" > mensaje.txt

      - uses: actions/upload-artifact@v4
        with:
          name: mensaje
          path: mensaje.txt

  consume:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mensaje

      - run: cat mensaje.txt
